value = input('Digite algo: ')

print('-----------------')
print('_________________')

print('o tipo primitivo? R: ', type(value))
print('_________________')
print('alphanumerico? R: ', value.isalpha())
print('_________________')
print('e um numero decimal? R: ', value.isdecimal())
print('_________________')
print('minusculo? R: ', value.islower())
print('_________________')
print('maiusculo? R: ', value.isupper())
print('_________________')
print('numerico? R: ', value.isnumeric())
print('_________________')
print('possíivel imprimir? R: ', value.isprintable())
print('_________________')